spring.application.name=backend-mini-mindforge

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/Mini_mindforge?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Thejas@ks123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.show-sql=false

# Gemini AI
gemini.api.key=AIzaSyAgCyfiCm_O7zQhhlBJuyIYo-vGJVMlads

# Server
server.port=8080

# File Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Logging
logging.level.com.thejas=INFO
logging.level.org.springframework.security=WARN
